version: "3.9"
services:
  main_bot:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_MAIN_BOT_TOKEN}
    tty: true
    restart: always
    command: python -m bot settings users servicing_posts bot_messages find_friends


  report_bot:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_REPORT_BOT_TOKEN}
    tty: true
    restart: always
    command: python -m bot reports tickets unban_tickets

  voice_bot:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_VOICE_BOT_TOKEN}
    tty: true
    restart: always
    command: python -m bot voice_channels voice_activity voice_records

  monitoring_bot:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_MONITORING_BOT_TOKEN}
    tty: true
    restart: always
    command: python -m bot info_provider server_status banner_updater

  auto_moderation_bot:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_AUTO_MODERATION_BOT_TOKEN}
    tty: true
    restart: always
    command: python -m bot auto_moderation

  image-generator:
    image: ghcr.io/mahryct3/magic-rust-discord-bot:$CI_COMMIT_SHORT_SHA-image-generator
    volumes:
      - /opt/magic-rust-discord-bot/.env:/app/.env
    build:
      dockerfile: ./image_generator/Dockerfile
    tty: true
    restart: always
    command: python -m image_generator


  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - ./storage/redis:/data