name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - ci_cd

env:
  CONTAINER_RELEASE_IMAGE: ghcr.io/mahryct3/magic-rust-discord-bot:${{ github.sha }}-image-generator
  CONTAINER_IMAGE_GENERATOR_IMAGE: ghcr.io/mahryct3/magic-rust-discord-bot:${{ github.ref_name }}-image-generator
  CONTAINER_OLD_IMAGE_GENERATOR_IMAGE: ghcr.io/mahryct3/magic-rust-discord-bot:image-generator-old

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          if docker pull CONTAINER_IMAGE_GENERATOR_IMAGE; then
            echo "Existing image found for CONTAINER_IMAGE_GENERATOR_IMAGE"
            docker build --cache-from CONTAINER_IMAGE_GENERATOR_IMAGE -f image_generator/Dockerfile -t $CONTAINER_RELEASE_IMAGE .
            docker push $CONTAINER_RELEASE_IMAGE
            docker tag CONTAINER_IMAGE_GENERATOR_IMAGE CONTAINER_OLD_IMAGE_GENERATOR_IMAGE
            docker push CONTAINER_OLD_IMAGE_GENERATOR_IMAGE
            docker tag $CONTAINER_RELEASE_IMAGE CONTAINER_IMAGE_GENERATOR_IMAGE
            docker push CONTAINER_IMAGE_GENERATOR_IMAGE
          else
            echo "No existing image found for CONTAINER_IMAGE_GENERATOR_IMAGE"
            docker build --cache-from CONTAINER_IMAGE_GENERATOR_IMAGE -f image_generator/Dockerfile -t CONTAINER_IMAGE_GENERATOR_IMAGE .
            docker push CONTAINER_IMAGE_GENERATOR_IMAGE
          fi