name: Deploy prod
on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and Run"
    runs-on: ubuntu-20.04
    steps:
      - name: Connect and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd magic-rust-discord-bot/
            git pull
            echo ${{ secrets.PROD_ENV }} > .env
            docker compose build
            docker compose down
            docker compose up -d
            docker image prune