name: Deploy prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Run"
    env:
      PROD_ENV_FILE: ${{ secrets.PROD_ENV }}
    runs-on: ubuntu-20.04
    steps:
      - name: Connect and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.PROD_ENV }}" > /tmp/.environment
            scp /tmp/.environment ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/magic-rust-discord-bot/.environment
            scp docker-compose.prod.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/magic-rust-discord-bot/docker-compose.yml
            scp deploy.sh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/magic-rust-discord-bot/deploy.sh
            ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
              CI_COMMIT_SHORT_SHA=${{ github.sha }}
              bash /opt/magic-rust-discord-bot/deploy.sh
            EOF